// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

//import { application } from "./application"

//import HelloController from "./hello_controller"
//application.register("hello", HelloController)

//import NavbarController from "./navbar_controller"
//application.register("navbar", NavbarController)

// Import and register all your controllers from the importmap via controllers/**/*_controller
import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)